### ISSUE TITLE
Build fails when running on Fedora host

### ISSUE THREAD

**Issue by rgeary1** [stucki/docker-cyanogenmod#6]
Running on a Fedora host, the kernel is built with SELinux.  The docker build script fails on the useradd command due to this Ubuntu issue : http://www.fewbytes.com/docker-selinux-and-the-myth-of-kernel-indipendence/

Fix is to replace this

    #RUN useradd --create-home cmbuild

with this :

    RUN mkdir -p /home/cmbuild && useradd --no-create-home cmbuild && rsync -a /etc/skel/ /home/cmbuild && chown -R cmbuild:cmbuild /home/cmbuild

**Comment by stucki** [comment]
Thanks for the report! I hope this workaround fixes the issue.
